version: '3'

services:
  db:
    image: mysql:5.7
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: readonlyuser
      MYSQL_PASSWORD: readonlypassword
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - db
    container_name: my_php_container

volumes:
  db_data:
